CREATE TABLE IF NOT EXISTS `purchase_orders` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `po_code` VARCHAR(40) NOT NULL,
  `supplier_name` VARCHAR(255) NOT NULL,
  `supplier_tax_code` VARCHAR(50) NOT NULL,
  `supplier_address` VARCHAR(255) NOT NULL,
  `supplier_phone` VARCHAR(32) DEFAULT NULL,
  `supplier_email` VARCHAR(255) DEFAULT NULL,
  `invoice_number` VARCHAR(100) NOT NULL,
  `invoice_date` DATE NOT NULL,
  `contract_number` VARCHAR(100) DEFAULT NULL,
  `delivery_note_number` VARCHAR(100) DEFAULT NULL,
  `received_by` VARCHAR(255) NOT NULL,
  `status` VARCHAR(20) NOT NULL DEFAULT 'FINALIZED',
  `item_count` INT NOT NULL DEFAULT 0,
  `quantity` INT NOT NULL,
  `unit_cost` DECIMAL(15,2) NOT NULL,
  `subtotal_amount` DECIMAL(15,2) NOT NULL,
  `vat_rate` DECIMAL(5,2) NOT NULL DEFAULT 0.00,
  `vat_amount` DECIMAL(15,2) NOT NULL DEFAULT 0.00,
  `total_amount` DECIMAL(15,2) NOT NULL,
  `product_id` BIGINT DEFAULT NULL,
  `product_name` VARCHAR(255) DEFAULT NULL,
  `stock_before` INT DEFAULT NULL,
  `stock_after` INT DEFAULT NULL,
  `notes` TEXT NULL,
  `created_by` BIGINT DEFAULT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_purchase_orders_po_code` (`po_code`),
  KEY `idx_purchase_orders_product_id` (`product_id`),
  KEY `idx_purchase_orders_invoice_number` (`invoice_number`),
  KEY `idx_purchase_orders_supplier_tax_code` (`supplier_tax_code`),
  KEY `idx_purchase_orders_created_by` (`created_by`),
  KEY `idx_purchase_orders_created_at` (`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `purchase_order_items` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `purchase_order_id` BIGINT NOT NULL,
  `product_id` BIGINT NOT NULL,
  `product_name` VARCHAR(255) NOT NULL,
  `quantity` INT NOT NULL,
  `unit_cost` DECIMAL(15,2) NOT NULL,
  `line_amount` DECIMAL(15,2) NOT NULL,
  `stock_before` INT NOT NULL,
  `stock_after` INT NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_purchase_order_items_order_product` (`purchase_order_id`, `product_id`),
  KEY `idx_purchase_order_items_product_id` (`product_id`),
  CONSTRAINT `fk_purchase_order_items_purchase_order`
    FOREIGN KEY (`purchase_order_id`) REFERENCES `purchase_orders` (`id`)
    ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
